### ISSUE TITLE
Sort By case sensitive

### ISSUE THREAD

**Issue by jrazmi** [gpsimpact/census-relational-organizing-backend#90]
Not sure if this is a super easy fix or very complicated... but we should probably make String Fields sort order not case sensitive.  
![Screen Shot 2019-04-23 at 9 19 50 AM](https://user-images.githubusercontent.com/11875591/56588663-6d59f080-65a9-11e9-87c2-a7e06ffc3c71.png)

**Comment by jakelowen** [comment]
I've looked into this some and there is an obstacle I need to think through. Currently my query builder reuses certain expressions across types. To postgres you can do `cat = dog` (string) or `3 = 4` (int)

If I just straight up coerce to `UPPER()` those functions cease to be reusable across types because PG will throw an error if attempt to upper an int.  i.e. `UPPER(3)` 

So what I'd need to do here is to go back and figure out how to split out my query builder into different type operations.  I think I can do this, but I'll probably prioritize other more pressing matters and come back to this later.

**Comment by jakelowen** [comment]
```
Teams Query:
Sort order is case sensitive:
was sorted by {"name":"ASC"} but lower case comes after uppercase A-Z
0: {id: "493fa89a-9a07-42a3-a0ae-5a48702090bd", name: "Fooss", description: "Foo Team description.s",…}
1: {id: "feb66bcd-b90b-4745-9e8b-431c2ef75d6d", name: "Greenfield 2019", description: "asdfasdf",…}
2: {id: "ceb39ea6-0a05-4e16-9170-96ecb6151a15", name: "fasdf asdfasdf", description: "asdf sdfg asdf",…}
3: {id: "a49ca9a3-a53a-4337-bcfc-1a77d0c41d97", name: "we", description: "asdf", active: true, slug: "we",…}
```

**Comment by jakelowen** [comment]
@jrazmi - Would you object to me scrapping the complicated nestable filtering and trying out the postgres full text search we've previously discussed (https://www.youtube.com/watch?v=szfUbzsKvtE)?

Unfortunately it would make your really cool dynamic search UI no longer necessary, It seems maybe overkill for this teams search where name is really the only searchable thing in the UI now.

I'm thinking we start with just the teams search and if we like it, we can discuss adding the same approach to a targets query.

Cool?
